# Generated by Django 2.0.4 on 2019-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('country', models.IntegerField(default=0)),
                ('city', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('telphone', models.CharField(max_length=255)),
                ('is_default', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Admin_Roles',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin_roles',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('pic', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'advertising',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('first', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=255)),
                ('b_logo', models.CharField(max_length=255)),
                ('story', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
                ('is_show', models.IntegerField(default=0)),
                ('is_company', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=255)),
                ('sp1', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Cate_attribute',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cate_attribute',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('is_nav_status', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('sort', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=255)),
                ('count_danwei', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ceckil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'ceckil',
            },
        ),
        migrations.CreateModel(
            name='Ceckil_activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'ceckil_activity',
            },
        ),
        migrations.CreateModel(
            name='Ceckil_goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('goods_code', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('ceckil_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ceckil_number', models.IntegerField()),
                ('limitation_number', models.IntegerField()),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'ceckil_goods',
            },
        ),
        migrations.CreateModel(
            name='Comment_zan',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'comment_zan',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('pingtai', models.IntegerField()),
                ('faxing', models.IntegerField()),
                ('miane', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limit', models.IntegerField()),
                ('doorsill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('goods_use', models.IntegerField()),
                ('describe', models.CharField(max_length=255)),
                ('state', models.IntegerField()),
                ('neck_number', models.IntegerField(default=0)),
                ('stay_number', models.IntegerField(default=0)),
                ('unused_number', models.IntegerField(default=0)),
                ('use_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='Coupon_cate',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_id', models.ForeignKey(on_delete='CASCADE', related_name='category_id', to='myadmin.Category')),
                ('coupon_id', models.ForeignKey(on_delete='CASCADE', related_name='coup_id', to='myadmin.Coupon')),
            ],
            options={
                'db_table': 'coupon_cate',
            },
        ),
        migrations.CreateModel(
            name='Dingdan_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flashOrderOvertime', models.IntegerField(default=0)),
                ('normalOrderOvertime', models.IntegerField(default=0)),
                ('confirmOvertime', models.IntegerField(default=0)),
                ('finishOvertime', models.IntegerField(default=0)),
                ('commentOvertime', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dingdan_setting',
            },
        ),
        migrations.CreateModel(
            name='Discourse_award',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('discourse_id', models.IntegerField()),
                ('discrip', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('Type', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('label_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'discourse_award',
            },
        ),
        migrations.CreateModel(
            name='Discourse_category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'discourse_category',
            },
        ),
        migrations.CreateModel(
            name='Discourse_collect',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'discourse_collect',
            },
        ),
        migrations.CreateModel(
            name='Discourse_comment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
                ('discourse_id', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('pid', models.IntegerField(default=0)),
                ('total_zan', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'discourse_comment',
            },
        ),
        migrations.CreateModel(
            name='Discourse_comment_img',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discourse_comment_id', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'discourse_comment_img',
            },
        ),
        migrations.CreateModel(
            name='Discourse_detail',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('is_hort', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
                ('collect_sum', models.IntegerField(default=0)),
                ('read_sum', models.IntegerField(default=0)),
                ('evaluate_sum', models.IntegerField(default=0)),
                ('is_show', models.IntegerField(default=0)),
                ('dc_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'discourse_detail',
            },
        ),
        migrations.CreateModel(
            name='Discourse_label',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discourse_detail_id', models.ForeignKey(on_delete='CASCADE', related_name='discourse_detail_id', to='myadmin.Discourse_detail')),
            ],
            options={
                'db_table': 'discourse_label',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_id', models.IntegerField()),
                ('cate_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField(default=0)),
                ('brand_name', models.CharField(max_length=255)),
                ('descrip', models.CharField(max_length=255)),
                ('goods_code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('low_stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sort', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('growht', models.IntegerField(default=0)),
                ('use_point_limit', models.IntegerField(default=0)),
                ('is_preview', models.IntegerField(default=0)),
                ('is_pubilsh', models.IntegerField(default=0)),
                ('is_new', models.IntegerField(default=0)),
                ('detail_title', models.CharField(max_length=255)),
                ('deatail_descrip', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('goods_type_id', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Goods_attribute_stock',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('sku_code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('low_stock', models.IntegerField(default=0)),
                ('sp1', models.CharField(max_length=255)),
                ('sp2', models.CharField(max_length=255)),
                ('sp3', models.CharField(max_length=255)),
                ('sale', models.IntegerField(default=0)),
                ('lock_stocp', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goods_attribute_stock',
            },
        ),
        migrations.CreateModel(
            name='Goods_attribute_value',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'goods_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='Goods_coupon',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.ForeignKey(on_delete='CASCADE', related_name='cou_id', to='myadmin.Coupon')),
                ('goods_id', models.ForeignKey(on_delete='CASCADE', related_name='goods_id', to='myadmin.Goods')),
            ],
            options={
                'db_table': 'goods_coupon',
            },
        ),
        migrations.CreateModel(
            name='Goods_fight',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('pro_count', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'goods_fight',
            },
        ),
        migrations.CreateModel(
            name='Goods_full_price',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reduce_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'goods_full_price',
            },
        ),
        migrations.CreateModel(
            name='Goods_member_price',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('member_level_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('member_level_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'goods_member_price',
            },
        ),
        migrations.CreateModel(
            name='Goods_pics',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'goods_pics',
            },
        ),
        migrations.CreateModel(
            name='Goods_sales_price',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('promote_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField()),
            ],
            options={
                'db_table': 'goods_sales_price',
            },
        ),
        migrations.CreateModel(
            name='Goods_type',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('attribute_count', models.IntegerField(default=0)),
                ('param_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='Goods_type_attribute',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filter_type', models.IntegerField(default=1)),
                ('is_select', models.IntegerField(default=0)),
                ('related_status', models.IntegerField(default=0)),
                ('select_type', models.IntegerField()),
                ('input_type', models.IntegerField(default=0)),
                ('input_list', models.CharField(default='', max_length=255)),
                ('hand_add_status', models.IntegerField(default=0)),
                ('sort', models.IntegerField()),
                ('type', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete='CASCADE', related_name='type_id', to='myadmin.Goods_type')),
            ],
            options={
                'db_table': 'goods_type_attribute',
            },
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'growth',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Like_category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(on_delete='CASCADE', related_name='c_id', to='myadmin.Category')),
            ],
            options={
                'db_table': 'like_category',
            },
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manage',
            },
        ),
        migrations.CreateModel(
            name='member_grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'member_grade',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Quentum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'quentum',
            },
        ),
        migrations.CreateModel(
            name='Role_Permission',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_id', models.ForeignKey(on_delete='CASCADE', related_name='permission_id', to='myadmin.Permission')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sadmins',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('login_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sadmins',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_sum', models.IntegerField(default=0)),
                ('recommend', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('collection_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'special',
            },
        ),
        migrations.CreateModel(
            name='Special_category',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('recommend', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'special_category',
            },
        ),
        migrations.CreateModel(
            name='Special_pic',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('special_id', models.IntegerField()),
                ('pic', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'special_pic',
            },
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'super',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('login_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_concern_brand',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_id', models.ForeignKey(on_delete='CASCADE', related_name='brand_id', to='myadmin.Brand')),
                ('user_id', models.ForeignKey(on_delete='CASCADE', related_name='user_brand_id', to='myadmin.User')),
            ],
            options={
                'db_table': 'user_concern_brand',
            },
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('sex', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('personalized', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('growth', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
        migrations.CreateModel(
            name='User_label',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('stoptime', models.DateTimeField()),
                ('coupon_code', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_label',
            },
        ),
        migrations.CreateModel(
            name='User_orders',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_sn', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coupon_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pay_type', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('pay_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
        migrations.AddField(
            model_name='role_permission',
            name='role_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='role_id', to='myadmin.Roles'),
        ),
        migrations.AddField(
            model_name='like_category',
            name='user_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='yonghu_id', to='myadmin.User'),
        ),
        migrations.AddField(
            model_name='goods_attribute_value',
            name='attribute_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='attribute_id', to='myadmin.Goods_type_attribute'),
        ),
        migrations.AddField(
            model_name='goods_attribute_value',
            name='goods_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='g_id', to='myadmin.Goods'),
        ),
        migrations.AddField(
            model_name='discourse_label',
            name='label_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='label_id', to='myadmin.Label'),
        ),
        migrations.AddField(
            model_name='discourse_collect',
            name='discourse_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='discourse_id', to='myadmin.Discourse_detail'),
        ),
        migrations.AddField(
            model_name='discourse_collect',
            name='user_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='user_id', to='myadmin.User'),
        ),
        migrations.AddField(
            model_name='comment_zan',
            name='discourse_comment_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='dc_id', to='myadmin.Discourse_comment'),
        ),
        migrations.AddField(
            model_name='comment_zan',
            name='user_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='u_id', to='myadmin.User'),
        ),
        migrations.AddField(
            model_name='cate_attribute',
            name='cate_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='cate_id', to='myadmin.Category'),
        ),
        migrations.AddField(
            model_name='cate_attribute',
            name='goods_type_attribute_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='goods_type_attribute_id', to='myadmin.Goods_type_attribute'),
        ),
        migrations.AddField(
            model_name='admin_roles',
            name='admin_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='admin_role', to='myadmin.Sadmins'),
        ),
        migrations.AddField(
            model_name='admin_roles',
            name='role_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='role_res', to='myadmin.Roles'),
        ),
    ]
